name: Automated Testing

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, 'feat/*', 'fix/*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run unit tests
        run: npm run test:unit || echo 'Unit tests skipped - not configured yet'
        
      - name: Run integration tests
        run: npm run test:integration || echo 'Integration tests skipped - not configured yet'
        
      - name: Run E2E tests
        run: npm run test:e2e || echo 'E2E tests skipped - not configured yet'
        
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
